services:
  postgres:
    image: postgres:16
    container_name: commerce_bank_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: commerce_bank
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: